# Generated by Django 2.2.2 on 2019-07-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ppo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('img2', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('img3', models.ImageField(upload_to='photos/%y/%m/%d/')),
            ],
        ),
    ]
