# Generated by Django 2.2.2 on 2019-07-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppo',
            old_name='img1',
            new_name='img_1',
        ),
        migrations.RenameField(
            model_name='ppo',
            old_name='img2',
            new_name='img_2',
        ),
        migrations.RenameField(
            model_name='ppo',
            old_name='img3',
            new_name='img_3',
        ),
    ]
