# Generated by Django 2.2.2 on 2019-07-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('photo_main', models.ImageField(upload_to='photos/%y/%m/%d/')),
            ],
        ),
    ]
